### ISSUE TITLE
Getting error while installing deps

### ISSUE THREAD

**Issue by dm-khanin** [ShopBonsai/no-hassle#73]
Hi everyone. I'm trying to install Node.js deps including `no-hassle` package through [heroku-buildpack-nodejs](https://github.com/heroku/heroku-buildpack-nodejs) and getting this error log

`-----> Installing dependencies`
`       Installing node modules`
`       npm ERR! Error while executing:`
`       npm ERR! /usr/bin/git ls-remote -h -t git://github.com/ShopBonsai/joi-to-swagger.git`
`       npm ERR! `
`       npm ERR! fatal: remote error: `
`       npm ERR!   The unauthenticated git protocol on port 9418 is no longer supported.`

Seems the reason of this is `no-hassle`'s `joi-to-swagger` dependency and it was installed as
`"joi-to-swagger": "git://github.com/ShopBonsai/joi-to-swagger.git",`

Is it possible to use standard version in `package.json`?

**Comment by KameronSturgess** [comment]
Fixed in https://github.com/ShopBonsai/no-hassle/pull/74
